apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-marcus-website
  description: Artist main website
  annotations:
    backstage.io/source-template: template:default/react-ssr-template
    terraform/organization: marcus
    terraform/workspaces: workspace-prod,workspace-staging
spec:
  type: website
  lifecycle: production
  owner: team-a
  system: marcus-portal
  consumesApis: ['component:backstage-marcus-lib']